{{- if .Values.runner.dind.registryMirrors }}
{{- include "bitbucketRunnerAutoscaler.runnerNamespaces" . }}
{{- range $namespace := .RunnerNamespaces }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitbucketRunnerAutoscaler.fullname" $ }}-dind
  namespace: {{ $namespace }}
  labels:
    {{- include "bitbucketRunnerAutoscaler.labels" $ | nindent 4 }}
data:
  daemon.json: |
    {
      "registry-mirrors": {{ $.Values.runner.dind.registryMirrors | toJson }}
    }
{{- end }}
{{- end }}
